# https://swagger.io/docs/specification/about/
openapi: 3.0.1
info:
  title: RestRserve OpenAPI
  version: '1.0'
servers:
  - url: /
paths:
  /fib:
    get:
      description: Calculates Fibonacci number
      parameters:
        - name: "n"
          description: >-
            x for Fibonnacci number. Example: <br>
            n = 0, 1, 2, 3, 4, 5, 6,  7,  8,  9, 10, ... <br>
            x = 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, ...
          in: query
          schema:
            type: integer
          example: 10
          required: true
      responses:
        200:
          description: API response
          content:
            text/plain:
              schema:
                type: string
                example: 5
        400:
          description: Bad Request
