services:
  ######################################################
  # R Testing
  ######################################################
  r-test:
    image: package/microservice:4.0.5
    build:
      context: ./
      dockerfile: ./.dev/docker/r-test/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_package
    restart: "no"
version: "3.8"
networks:
  default:
    name: r-package
