services:
  ######################################################
  # R Testing
  ######################################################
  r-test:
    image: r-package/microservices
    build:
      context: ./
      dockerfile: ./.dev/docker/r-test/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_test
    restart: "no"
  ######################################################
  # R Plumber
  ######################################################
  r-plumber:
    image: microservice/plumber:1.0.0
    build:
      context: ./
      dockerfile: ./.dev/docker/r-plumber/Dockerfile
      args:
        - R_REPOS='https://mran.microsoft.com/snapshot/2021-08-10'
    container_name: r_plumber
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
version: "3.3"
# networks:
#   default:
#     name: r-package
